name: tobeto
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

#---------------- PACKAGES ----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8

  # Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  iconsax: ^0.0.8

  # State Managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_calendar: ^21.2.3
  percent_indicator: ^4.2.3
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5

  # Product Specific

#---------------- ./ PACKAGES END ----------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/auth/
    - assets/images/onboarding/

  fonts:
    - family: Tinos
      fonts:
        - asset: assets/fonts/Tinos-Light.ttf
          weight: 300
        - asset: assets/fonts/Tinos-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tinos-Italic.ttf
          style: italic
        - asset: assets/fonts/Tinos-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tinos-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Tinos-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Tinos-Bold.ttf
          weight: 800
        - asset: assets/fonts/Tinos-BoldItalic.ttf
          weight: 800
          style: italic
