// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56WawlCdypS0os3zi3-imAwHFTisI1Bc',
    appId: '1:106558966363:web:3f421c82d7e2c1cc660d7e',
    messagingSenderId: '106558966363',
    projectId: 'tobetoapp-5b412',
    authDomain: 'tobetoapp-5b412.firebaseapp.com',
    storageBucket: 'tobetoapp-5b412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE1RAm5UAykzqxdTUhIA8PY7jEWAxIFOQ',
    appId: '1:106558966363:android:3675e17b8a27a0bc660d7e',
    messagingSenderId: '106558966363',
    projectId: 'tobetoapp-5b412',
    storageBucket: 'tobetoapp-5b412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wLXBE3a6R87WKTwXjPRkSOugwXNf76g',
    appId: '1:106558966363:ios:fae1c5fad556e79a660d7e',
    messagingSenderId: '106558966363',
    projectId: 'tobetoapp-5b412',
    storageBucket: 'tobetoapp-5b412.appspot.com',
    iosBundleId: 'com.example.tobeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wLXBE3a6R87WKTwXjPRkSOugwXNf76g',
    appId: '1:106558966363:ios:7113b77c4cb78434660d7e',
    messagingSenderId: '106558966363',
    projectId: 'tobetoapp-5b412',
    storageBucket: 'tobetoapp-5b412.appspot.com',
    iosBundleId: 'com.example.tobeto.RunnerTests',
  );
}
